### ISSUE TITLE
pin field does not automatically have focus

### ISSUE THREAD

**Issue by eighthave** [iilab/PanicButton#56]
Here is a little usability nitpick: when you long-press to get to the pin screen, the pin code text field does not have focus.  That means I have to click on the text field before I can entire my pin code.  Since that screen does nothing else. the textfield should have focus.  I think its something you can set in the XML for that layout.  something like `<requestFocus/>`.

**Comment by jmatsushita** [comment]
Thanks for the report! This is fixed on the dev branch and will be released soon on the playstore.
