### ISSUE TITLE
Improve website copy (re: Android versions)

### ISSUE THREAD

**Issue by patcon** [iilab/PanicButton#77]
https://imgur.com/7u3976O

2.3.3 to 4.4.2 is about the same as "Gingerbread to KitKat", which most users would have a much better idea of what they fall within :)

(Sorry, couldn't find website code repo, though that would be a better place to post.)

**Comment by jmatsushita** [comment]
Thanks for the feedback! 
![image](https://cloud.githubusercontent.com/assets/356097/7234829/45ade93e-e78a-11e4-8bfb-74f1c76e73da.png)
